# Generated by Django 5.1 on 2024-08-14 12:39

import django_countries.fields
import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='full name', max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('current_status', models.CharField(choices=[('A', 'Fresh graduate'), ('B', 'Final year student')], default='A')),
                ('university', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('publicity_awareness', models.CharField(choices=[('M', 'Male'), ('F', 'Female')])),
                ('career_goals', models.TextField(max_length=255)),
                ('previous_attendance', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y')),
                ('topic_of_interest', models.TextField(max_length=300)),
                ('availiability', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y')),
                ('whatsapp_no', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('teligram_no', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('comments_or_question', models.TextField(max_length=500)),
            ],
        ),
    ]
