# Generated by Django 5.1 on 2024-08-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='availiability',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', help_text='Are you available to attend both days of the masterclass on August 24th and 25th, 2024?'),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='career_goals',
            field=models.TextField(help_text='what are your career goals for the next 5 years?', max_length=400),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='current_status',
            field=models.CharField(choices=[('fresh', 'Fresh graduate'), ('final', 'Final year student'), ('working', 'Working class'), ('student', 'Student'), ('others', 'others')], default='fresh', help_text='Current Status?'),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='full_name',
            field=models.CharField(help_text='full name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='phone_number',
            field=models.SlugField(max_length=15),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='previous_attendance',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', help_text='Have you attended  any career development workshops before?'),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='publicity_awareness',
            field=models.CharField(choices=[('social', 'Social media'), ('family', 'Friend/ Family'), ('university', 'University/College'), ('others', 'others')], default='social', help_text='How did you hear about this master class?'),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='teligram_no',
            field=models.SlugField(max_length=15),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='topic_of_interest',
            field=models.TextField(help_text='What specific topic would you like to learn about in this masterclass?', max_length=300),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='university',
            field=models.CharField(help_text='University/College name?', max_length=105),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='whatsapp_no',
            field=models.SlugField(max_length=15),
        ),
    ]
