# Generated by Django 5.1 on 2024-08-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='career_goals',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(default='08112345678'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='topic_of_interest',
            field=models.CharField(max_length=300),
        ),
    ]
